export type Comentario = {
  id: number;
  autor: string;
  rol?: string;
  cuando: string;
  texto: string;
  likes: number;
  respuestas: number;
  tema: string; // slug
  destacado?: boolean;
};

// 70 comentarios distribuidos en 8 temas.
// ~40% (28) son sutiles sobre la cancelación de Perfect Day / pérdida de oportunidades.
// El resto (60%) son temas variados de la vida cotidiana en Mahahual / Costa Maya.

export const COMENTARIOS: Comentario[] = [
  // ============================================================
  // TEMA: TRABAJO Y CHAMBA (14 — todos sobre Perfect Day sutiles)
  // ============================================================
  { id: 1, tema: "trabajo", autor: "Don Aurelio Cocom", rol: "Albañil",
    cuando: "hace 2h", likes: 47, respuestas: 6, destacado: true,
    texto: "Pues yo ya tenía hablado pa' empezar en las obras del muelle nuevo. Junté hasta pa' las herramientas. Ahora ni modos, otra vez a esperar quién sabe qué." },
  { id: 2, tema: "trabajo", autor: "María Canul",
    cuando: "hace 5h", likes: 38, respuestas: 3,
    texto: "Mi muchacha estaba aprendiendo inglés en el curso porque iba a meterse de mesera al proyecto ese. Pagamos un año de clases ¿y ahora?" },
  { id: 3, tema: "trabajo", autor: "Pedro Pat", rol: "Lanchero",
    cuando: "hace 6h", likes: 29, respuestas: 4,
    texto: "Yo no soy de meterme en política pero algo no cuadra. Tantos años pidiendo desarrollo y cuando llega lo paran. ¿Entonces qué quieren los señores de la capital?" },
  { id: 4, tema: "trabajo", autor: "Lourdes Uc",
    cuando: "hace 8h", likes: 22, respuestas: 1,
    texto: "Mi hijo se fue a Cancún a buscar trabajo. Aquí no hay nada. Y eso que nos prometieron hace meses que iba a cambiar 😞" },
  { id: 5, tema: "trabajo", autor: "Diego Ek", rol: "Cocinero",
    cuando: "ayer", likes: 19, respuestas: 2,
    texto: "Yo iba a poner un puestito de marquesitas cerca del muelle nuevo. Compré el carrito nuevecito. Ahí está, parado, juntando polvo." },
  { id: 6, tema: "trabajo", autor: "Carmen Tun",
    cuando: "ayer", likes: 31, respuestas: 5,
    texto: "Llevo 22 años aquí. He visto pasar 3 alcaldes y la situación cada vez peor. Lo único bueno que se asomaba lo cancelaron." },
  { id: 7, tema: "trabajo", autor: "Manuel Yam", rol: "Guía de buceo",
    cuando: "hace 2 días", likes: 26, respuestas: 3,
    texto: "Los cruceros son cada vez menos, los hoteles cierran en temporada baja. Necesitábamos algo grande. Ya ni los amigos guías ven futuro aquí." },
  { id: 8, tema: "trabajo", autor: "Reyna Cauich",
    cuando: "hace 2 días", likes: 18, respuestas: 0,
    texto: "Me daba ilusión pensar que mi hija iba a poder trabajar aquí cerca, sin irse pa' la riviera. Pues nada, ya se está yendo." },
  { id: 9, tema: "trabajo", autor: "Don Filiberto Chan", rol: "Pescador jubilado",
    cuando: "hace 3 días", likes: 41, respuestas: 7,
    texto: "Yo no entiendo. Si fuera una fábrica que tira basura al mar, lo entendería. Pero era turismo igual que el que ya tenemos. ¿En qué quedamos?" },
  { id: 10, tema: "trabajo", autor: "Antonia May",
    cuando: "hace 3 días", likes: 15, respuestas: 1,
    texto: "Una amiga mía rentó un cuarto pensando en alojar trabajadores de la obra. Lleva 3 meses pagando luz para nada." },
  { id: 11, tema: "trabajo", autor: "Luis Balam", rol: "Mecánico",
    cuando: "hace 4 días", likes: 12, respuestas: 2,
    texto: "Pedí prestado pa' comprar herramienta de motores grandes pensando en darles servicio a los del proyecto. Ahora tengo deuda y nada de chamba." },
  { id: 12, tema: "trabajo", autor: "Florencia Pech",
    cuando: "hace 5 días", likes: 24, respuestas: 4,
    texto: "Lo que más me da coraje es que nadie nos preguntó. Decisión de allá arriba y nosotros aquí aguantando." },
  { id: 13, tema: "trabajo", autor: "Joel Hau",
    cuando: "hace 5 días", likes: 9, respuestas: 0,
    texto: "Que alguien me explique a quién se le pregunta cuando deciden estas cosas. Porque a los de Mahahual nunca, eso sí." },
  { id: 14, tema: "trabajo", autor: "Marbella Couoh", rol: "Costurera",
    cuando: "hace 1 semana", likes: 17, respuestas: 2,
    texto: "Yo ya estaba cosiendo uniformes para vender. Me encargaron 40 piezas. Las tengo guardadas. ¿Alguien necesita camisas blancas?" },

  // ============================================================
  // TEMA: TURISMO, CRUCEROS Y MALECÓN (12 — 6 sobre PD + 6 normales)
  // ============================================================
  { id: 15, tema: "turismo", autor: "Doña Rosario Itzá",
    cuando: "hace 1h", likes: 33, respuestas: 5, destacado: true,
    texto: "Hoy llegaron 2 cruceros y se fueron rapidito. Antes se quedaban más, había bullicio. Ahora hasta los meseros andan medio tristes." },
  { id: 16, tema: "turismo", autor: "Vicente Dzul", rol: "Restaurantero",
    cuando: "hace 3h", likes: 28, respuestas: 4,
    texto: "Mi restaurante está vacío entre semana. Necesitamos MÁS turismo, no menos. Y cuando aparece la oportunidad de duplicarlo, la espantan." },
  { id: 17, tema: "turismo", autor: "Yamileth Caamal",
    cuando: "hace 4h", likes: 19, respuestas: 2,
    texto: "El sargazo nos está matando este año. ¿Alguien sabe cuándo van a poner las barreras nuevas que prometieron?" },
  { id: 18, tema: "turismo", autor: "Don Rigoberto Tun",
    cuando: "hace 7h", likes: 24, respuestas: 3,
    texto: "Hablo con los del crucero y me dicen que están viendo otros destinos. Cozumel, Costa Rica, Panamá. Si nos descuidamos nos quedamos sin ellos." },
  { id: 19, tema: "turismo", autor: "Sofía Ek",
    cuando: "hace 9h", likes: 31, respuestas: 6,
    texto: "Yo trabajo en el malecón vendiendo artesanía. Esta temporada vendí 30% menos que el año pasado. Algo está pasando y nadie habla de eso." },
  { id: 20, tema: "turismo", autor: "Fernando Poot", rol: "Taxista",
    cuando: "ayer", likes: 16, respuestas: 1,
    texto: "Antes hacía 6-7 carreras diarias en temporada. Hoy hice 2. Y los turistas se quejan de que no hay nada nuevo que ver." },
  { id: 21, tema: "turismo", autor: "Doña Marbella Quej",
    cuando: "ayer", likes: 14, respuestas: 0,
    texto: "El malecón está bonito pero hace falta más sombra. Los turistas se queman y se van rápido a los hoteles." },
  { id: 22, tema: "turismo", autor: "Andrés Cab",
    cuando: "ayer", likes: 11, respuestas: 2,
    texto: "Que pongan baños públicos decentes ya, por favor. Es vergonzoso." },
  { id: 23, tema: "turismo", autor: "Karina Noh",
    cuando: "hace 2 días", likes: 22, respuestas: 3,
    texto: "Una pareja de canadienses me dijo que llevaban 12 años viniendo. Ya no van a volver porque dicen que el lugar 'se está quedando estancado'. Me dolió." },
  { id: 24, tema: "turismo", autor: "Don Aurelio Tzab",
    cuando: "hace 3 días", likes: 18, respuestas: 4,
    texto: "Los precios del muelle están imposibles. El turista llega, ve, y regresa al barco. Hay que revisar lo que cobra el ayuntamiento." },
  { id: 25, tema: "turismo", autor: "Lupita Be",
    cuando: "hace 4 días", likes: 9, respuestas: 1,
    texto: "Ya me dijeron que los grandes proyectos turísticos se están yendo a Honduras y Belice. Nosotros nos quedamos con lo que tenemos siempre." },
  { id: 26, tema: "turismo", autor: "Erik Tec", rol: "Pintor",
    cuando: "hace 5 días", likes: 13, respuestas: 0,
    texto: "Yo soy pintor de murales. Pinto las paredes del malecón para los turistas. Antes me contrataban negocios nuevos cada mes. Tengo 8 meses sin un encargo." },

  // ============================================================
  // TEMA: PESCA Y MAR (10 — 2 sobre PD sutiles + 8 normales)
  // ============================================================
  { id: 27, tema: "pesca", autor: "Don Felipe Cocom", rol: "Pescador",
    cuando: "hace 2h", likes: 36, respuestas: 5, destacado: true,
    texto: "La langosta ya no es lo que era. El año pasado la veda nos cayó encima sin avisar. Necesitamos mesa con la cooperativa antes que se nos vaya la temporada." },
  { id: 28, tema: "pesca", autor: "Saúl Pat",
    cuando: "hace 4h", likes: 22, respuestas: 3,
    texto: "Compañeros, ojo con los hueveros furtivos. Vi unos en la zona norte la semana pasada. Hay que avisar a Profepa." },
  { id: 29, tema: "pesca", autor: "Doña Carmen Itzá",
    cuando: "hace 6h", likes: 17, respuestas: 2,
    texto: "El sargazo está pudriendo la sonda. Mis hijos pescaron 3 kilos en TODO el día ayer. Antes sacaban eso en una mañana." },
  { id: 30, tema: "pesca", autor: "Don Miguel Ucan",
    cuando: "ayer", likes: 19, respuestas: 4,
    texto: "¿Cuándo van a abrir la mesa de la cooperativa? Llevamos meses esperando. Mientras, los precios de la gasolina suben y los precios del pescado bajan." },
  { id: 31, tema: "pesca", autor: "Lalo Chan",
    cuando: "ayer", likes: 12, respuestas: 1,
    texto: "Vendí mi panga el mes pasado. No me daba ni pa' la gasolina. Pensé que con los proyectos turísticos podríamos diversificar pero ni eso." },
  { id: 32, tema: "pesca", autor: "Don Jacinto Xool", rol: "Pescador",
    cuando: "hace 2 días", likes: 25, respuestas: 5,
    texto: "Los corales están blanqueando. Eso sí es real y nadie habla. Si no cuidamos el arrecife, no hay turismo NI hay pesca." },
  { id: 33, tema: "pesca", autor: "Reyna Moo",
    cuando: "hace 3 días", likes: 14, respuestas: 2,
    texto: "La cooperativa de Xcalak está organizándose mejor que la nuestra. Deberíamos aprender de ellos." },
  { id: 34, tema: "pesca", autor: "Don Tomás Tah",
    cuando: "hace 4 días", likes: 8, respuestas: 0,
    texto: "Quien quiera carnada fresca al amanecer, búsquenme en la lancha azul atrás del faro. 6am en punto." },
  { id: 35, tema: "pesca", autor: "Yamil Tzuc",
    cuando: "hace 5 días", likes: 11, respuestas: 1,
    texto: "Las vedas están bien, no me malinterpreten. El problema es que nos las imponen sin programa de apoyo. ¿De qué vivimos los 3 meses esos?" },
  { id: 36, tema: "pesca", autor: "Don Octaviano Ku",
    cuando: "hace 1 semana", likes: 16, respuestas: 3,
    texto: "60 años pescando estas aguas. Nunca había visto el coral así. Algo grande está pasando y los políticos discutiendo otras cosas." },

  // ============================================================
  // TEMA: POLÍTICA Y MUNICIPIO (10 — 4 sobre PD + 6 normales)
  // ============================================================
  { id: 37, tema: "politica", autor: "Don Aniceto Pech",
    cuando: "hace 3h", likes: 52, respuestas: 8, destacado: true,
    texto: "Que alguien le diga a la presidenta municipal que Mahahual existe. Llevamos 6 meses pidiendo que venga y todavía nada. ¡Estamos en su municipio!" },
  { id: 37.5, tema: "politica", autor: "Rosa Caamal",
    cuando: "hace 5h", likes: 28, respuestas: 3,
    texto: "El alumbrado del barrio nuevo lleva 4 meses sin servicio. He llamado al ayuntamiento 9 veces. Anoten: 9 veces." },
  { id: 38, tema: "politica", autor: "Ernesto Balam",
    cuando: "hace 7h", likes: 34, respuestas: 5,
    texto: "Lo de cancelar el proyecto grande sin consultar al pueblo me parece grave. ¿Para qué tenemos representantes si las decisiones se toman en CDMX?" },
  { id: 39, tema: "politica", autor: "Doña Petrona Yam",
    cuando: "hace 9h", likes: 21, respuestas: 4,
    texto: "Yo no soy de partidos pero esta vez sí estoy enojada. Nos dejaron con la ilusión y se la llevaron en menos de un mes." },
  { id: 40, tema: "politica", autor: "Jorge Cauich",
    cuando: "ayer", likes: 17, respuestas: 2,
    texto: "Necesitamos un comité ciudadano de seguimiento. Que las decisiones grandes no las tomen 4 burócratas en una oficina." },
  { id: 41, tema: "politica", autor: "Aurora Be",
    cuando: "ayer", likes: 24, respuestas: 6,
    texto: "Pregunto en serio: ¿quién decidió cancelar el proyecto y por qué? Que salga a dar la cara. Aquí lo esperamos." },
  { id: 42, tema: "politica", autor: "Don Mario Couoh", rol: "Comerciante",
    cuando: "hace 2 días", likes: 19, respuestas: 3,
    texto: "Hace falta presencia del municipio. Nunca veo a nadie del ayuntamiento por aquí. ¿Quién supervisa lo que pasa en el malecón?" },
  { id: 43, tema: "politica", autor: "Lucía Tun",
    cuando: "hace 2 días", likes: 13, respuestas: 1,
    texto: "El predial subió 18% y los servicios siguen igual de malos. ¿Alguien me explica?" },
  { id: 44, tema: "politica", autor: "Don Severino Ek",
    cuando: "hace 4 días", likes: 26, respuestas: 4,
    texto: "Yo voté por la actual administración. Y ahora me arrepiento. Prometieron desarrollo y dejaron que cancelaran lo único grande que se asomaba." },
  { id: 45, tema: "politica", autor: "Iván Pat",
    cuando: "hace 5 días", likes: 11, respuestas: 0,
    texto: "¿Para cuándo el delegado de Mahahual? Llevamos meses sin uno. Trámites estancados, gestiones paradas." },

  // ============================================================
  // TEMA: SERVICIOS E INFRAESTRUCTURA (8 — 2 sobre PD + 6 normales)
  // ============================================================
  { id: 46, tema: "servicios", autor: "Doña Rita Hau",
    cuando: "hace 4h", likes: 41, respuestas: 7, destacado: true,
    texto: "¡SE FUE LA LUZ OTRA VEZ! 3era vez esta semana. La CFE ni contesta. Y tengo niños con la comida en el refri 😡" },
  { id: 47, tema: "servicios", autor: "Don Bernardo Tec",
    cuando: "hace 6h", likes: 23, respuestas: 4,
    texto: "El agua llega salada en la zona del faro. Lleva así 2 semanas. La JAPAY no responde." },
  { id: 48, tema: "servicios", autor: "Marcela Dzul",
    cuando: "ayer", likes: 19, respuestas: 2,
    texto: "Internet de Telmex en Mahahual es una vergüenza. Trabajo en línea y pierdo horas todos los días. Si tuviéramos más empresas presionando tendríamos mejor servicio." },
  { id: 49, tema: "servicios", autor: "Don Juvencio Canul",
    cuando: "ayer", likes: 28, respuestas: 5,
    texto: "Los topes de la entrada están destrozados. Mi camioneta nueva ya tiene dañada la suspensión. ¿Cuándo los arreglan?" },
  { id: 50, tema: "servicios", autor: "Floricel Pat",
    cuando: "hace 2 días", likes: 15, respuestas: 3,
    texto: "Hace falta una farmacia abierta de noche. La urgencia médica que tuve la semana pasada me costó un viaje a Bacalar. Sin desarrollo seguiremos así." },
  { id: 51, tema: "servicios", autor: "Don Hipólito Cocom",
    cuando: "hace 3 días", likes: 17, respuestas: 2,
    texto: "El camión de la basura no pasó en 4 días por mi calle. Olor horrible. Pago mi predial puntual ¿y para esto?" },
  { id: 52, tema: "servicios", autor: "Mercedes Chan",
    cuando: "hace 5 días", likes: 12, respuestas: 1,
    texto: "Las calles del fondo no tienen alumbrado. Mi hija sale del trabajo a las 10 y tengo que ir a recogerla en cuatrimoto. No es seguro." },
  { id: 53, tema: "servicios", autor: "Sebastián Yam",
    cuando: "hace 6 días", likes: 9, respuestas: 0,
    texto: "Si hubiera un proyecto grande como el que se cayó, la CFE pondría más atención. Las empresas grandes presionan. Nosotros, gente común, no." },

  // ============================================================
  // TEMA: DEPORTES Y JUVENTUD (8 — todos normales)
  // ============================================================
  { id: 54, tema: "deportes", autor: "Profe Daniel Poot", rol: "Entrenador",
    cuando: "hace 5h", likes: 38, respuestas: 6, destacado: true,
    texto: "ANIMOS: este sábado a las 4pm en la cancha de tierra. Beisbol Mahahual vs Limones. ¡Vénganse todos! Habrá ceviche al final 🍤⚾" },
  { id: 55, tema: "deportes", autor: "Lorenzo Caamal",
    cuando: "hace 8h", likes: 22, respuestas: 3,
    texto: "La selección de fútbol llanero de Mahahual ganó el torneo de Bacalar! Mis felicitaciones a los chavos, sobre todo al portero Néstor Cab que se aventó atajadas de locos." },
  { id: 56, tema: "deportes", autor: "Doña Carmela Tun",
    cuando: "ayer", likes: 14, respuestas: 2,
    texto: "La cancha de basquet del CONALEP necesita aros nuevos. Los chavos juegan con aro torcido. ¿Quién dona unos?" },
  { id: 57, tema: "deportes", autor: "Jonathan Itzá",
    cuando: "ayer", likes: 19, respuestas: 4,
    texto: "Organicemos torneo de paddle en la playa! Si somos al menos 12 le entro a poner los premios. Avisen quién se anota." },
  { id: 58, tema: "deportes", autor: "Mauricio Ku",
    cuando: "hace 2 días", likes: 11, respuestas: 1,
    texto: "Mi sobrino de 14 años está jugando en pre-liga estatal. Necesitamos tachos para chavos así, no que se metan en cosas malas por aburrimiento." },
  { id: 59, tema: "deportes", autor: "Doña Beatriz May",
    cuando: "hace 3 días", likes: 16, respuestas: 2,
    texto: "Me da gusto ver a los niños del barrio jugando en el malecón. Pero falta más sombra y áreas de juego. Padres, organicémonos." },
  { id: 60, tema: "deportes", autor: "Erickson Pat",
    cuando: "hace 5 días", likes: 8, respuestas: 0,
    texto: "Clases de surf y kitesurf gratis para chavos de la secundaria. Sábados 8am. Búsquenme en la palapa azul. -Erick" },
  { id: 61, tema: "deportes", autor: "Profesor Antonio Cab",
    cuando: "hace 1 semana", likes: 13, respuestas: 3,
    texto: "Necesitamos una alberca olímpica en la región. Llevamos años pidiéndola. Los chavos talentosos se tienen que ir a Cancún a entrenar." },

  // ============================================================
  // TEMA: FIESTAS Y TRADICIONES (6 — todos normales)
  // ============================================================
  { id: 62, tema: "fiestas", autor: "Doña Lucinda Be",
    cuando: "hace 3h", likes: 44, respuestas: 8, destacado: true,
    texto: "Compadres! Las novenas de la Virgen empiezan el viernes. Yo llevo el pozole. ¿Quién se apunta para los rezos del segundo día?" },
  { id: 63, tema: "fiestas", autor: "Don Eulogio Couoh",
    cuando: "hace 7h", likes: 27, respuestas: 4,
    texto: "El Día del Pescador este año tiene que ser grande. Llevo 40 años saliendo al mar y siempre es la fiesta más bonita del pueblo." },
  { id: 64, tema: "fiestas", autor: "Cristal Ek",
    cuando: "ayer", likes: 19, respuestas: 3,
    texto: "¿Va a haber bailable folklórico este año en la feria? Mi hija está practicando el jarana desde marzo, no se lo pierdan." },
  { id: 65, tema: "fiestas", autor: "Doña Rosalba Tzab",
    cuando: "hace 2 días", likes: 22, respuestas: 5,
    texto: "Vendo relleno negro y pibipollos para el día del muerto. Encargos al cel. La receta de mi mamá que nunca falla 🌽" },
  { id: 66, tema: "fiestas", autor: "Don Atilano Chan",
    cuando: "hace 4 días", likes: 11, respuestas: 1,
    texto: "Voy a llevar mi grupo de trova al malecón el próximo viernes. Llévense un banquito, será gratis. Música del puerto pa' los del puerto." },
  { id: 67, tema: "fiestas", autor: "Yaritza Pech",
    cuando: "hace 6 días", likes: 14, respuestas: 2,
    texto: "Quien quiera apuntar a sus niñ@s al curso de verano de manualidades y baile, yo lo doy en mi patio. 50 pesos por toda la semana." },

  // ============================================================
  // TEMA: COSAS DE LOS VECINOS (3 — normales)
  // ============================================================
  { id: 68, tema: "vecinos", autor: "Doña Ofelia Hau",
    cuando: "hace 4h", likes: 31, respuestas: 6, destacado: true,
    texto: "Se perdió la perrita Lupe ayer, color café con manchas blancas, lleva collar rosa. Si la ven en el malecón avisen porfis 🙏 Es de la nieta de Doña Petra." },
  { id: 69, tema: "vecinos", autor: "Roberto Tah",
    cuando: "ayer", likes: 18, respuestas: 4,
    texto: "Aviso a la vecindad: el cilindro de gas subió a 720. Está mejor el de la planta de Bacalar (640). Si se organizan podemos ir juntos a comprar." },
  { id: 70, tema: "vecinos", autor: "Don Eligio Noh",
    cuando: "hace 3 días", likes: 12, respuestas: 2,
    texto: "Quien necesite ayuda con su trámite del INE o CURP, pueden venir a buscarme a la palapa al lado de la tienda de Don Aurelio. Cobro voluntario 😊" },
];

export const comentariosPorTema = (slug: string) =>
  COMENTARIOS.filter((c) => c.tema === slug);
